export const SET_VERSION = "SET_VERSION";

export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_START = "ADD_ITEM_START";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";

export const REMOVE_ITEM = "REMOVE_ITEM";

export const TOGGLE_MODAL_FORM = "TOGGLE_MODAL_FORM";
export const SHOW_DESCRIPTION = "SHOW_DESCRIPTION";
export const TOGGLE_DELETE_POPUP = "TOGGLE_DELETE_POPUP";

export const FORM_RENDER = "FORM_RENDER";
export const FORM_INPUT_CHANGED = "FORM_INPUT_CHANGED";
export const FORM_EDIT_ITEM = "FORM_EDIT_ITEM";

export const AUTH_FORM_RENDER = "AUTH_FORM_RENDER";
export const AUTH_FORM_INPUT_CHANGED = "AUTH_FORM_INPUT_CHANGED";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_ITEMS_START = "FETCH_ITEMS_START";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAIL = "FETCH_ITEMS_FAIL";
