export const ADD_ITEM_TO_INCOME = "ADD_ITEM_TO_INCOME";
export const REMOVE_ITEM_FROM_INCOME = "REMOVE_ITEM_FROME_INCOME";

export const ADD_ITEM_TO_EXPENSE = "ADD_ITEM_TO_EXPENSE";
export const REMOVE_ITEM_FROM_EXPENSE = "REMOVE_ITEM_FROME_EXPENSE";

export const TOGGLE_MODAL_FORM = "TOGGLE_MODAL_FORM";
export const TOGGLE_MODAL_DESCRIPTION = "TOGGLE_MODAL_DESCRIPTION";
