export const SET_VERSION = "SET_VERSION";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const TOGGLE_MODAL_FORM = "TOGGLE_MODAL_FORM";
export const SHOW_DESCRIPTION = "SHOW_DESCRIPTION";
export const TOGGLE_DELETE_POPUP = "TOGGLE_DELETE_POPUP";

export const FORM_RENDER = "FORM_RENDER";
export const FORM_INPUT_CHANGED = "FORM_INPUT_CHANGED";
export const FORM_EDIT_ITEM = "FORM_EDIT_ITEM";

export const AUTH_FORM_RENDER = "AUTH_FORM_RENDER";
export const AUTH_FORM_INPUT_CHANGED = "AUTH_FORM_INPUT_CHANGED";
